config_map:
  - name: PROJECT_API_SERVICE_URI
    value: http://project-api.{{ project }}.svc:8080
  - name: PROJECT_BURNDOWN_SERVICE_URI
    value: http://project-burndown.{{ project }}.svc:8080
  - name: SPRINT_BOARD_API_SERVICE_URI
    value: http://sprint-board.{{ project }}.svc:8080
  - name: SPRINT_BURNDOWN_SERVICE_URI
    value: http://sprint-burndown.{{ project }}.svc:8080
  - name: SPRINT_API_SERVICE_URI
    value: http://sprint-api.{{ project }}.svc:8080
  - name: STORY_API_SERVICE_URI
    value: http://story-api.{{ project }}.svc:8080
  - name: TASK_API_SERVICE_URI
    value: http://task-api.{{ project }}.svc:8080
  - name: JAEGER_SERVICE_NAME
    value: {{ microservice.name }}
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: jaeger-agent.{{ project }}.svc:5778    
  - name: JAEGER_AGENT_HOST
    value: jaeger-agent.{{ product.name }}.svc      