config_map:
  - name: PROJECT_API_SERVICE_URI
    value: http://greenproject-api.{{ project }}.svc:8080
  - name: PROJECT_BURNDOWN_SERVICE_URI
    value: http://greenproject-burndown.{{ project }}.svc:8080
  - name: SPRINT_BOARD_API_SERVICE_URI
    value: http://greensprint-board.{{ project }}.svc:8080
  - name: SPRINT_BURNDOWN_SERVICE_URI
    value: http://greensprint-burndown.{{ project }}.svc:8080 
  - name: SPRINT_API_SERVICE_URI
    value: http://greensprint-api.{{ project }}.svc:8080
  - name: STORY_API_SERVICE_URI
    value: http://greenstory-api.{{ project }}.svc:8080
  - name: TASK_API_SERVICE_URI
    value: http://greentask-api.{{ project }}.svc:8080
  - name: JAEGER_SERVICE_NAME
    value: green-{{ microservice.name }}
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: jaeger-agent.{{ product.name }}-monitoring.svc:5778    
  - name: JAEGER_AGENT_HOST
    value: jaeger-agent.{{ product.name }}-monitoring.svc      