---
- name: Create Basic UI
  hosts: localhost
  vars_files:
    - microservice-vars.yml  
  tasks:
   
    - name: Login in Openshift
      shell: "oc login {{ openshift }} --insecure-skip-tls-verify=true -u {{ username }} -p {{ password }} -n {{ project }}"
      tags:
        - openshift
        
    - include_tasks: create-app-tasks.yml        