apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: pipeline
    name: release-basic-ui
  name: release-basic-ui
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: "https://github.com/Estafet-LTD/estafet-microservices-scrum-basic-ui"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: release-pipeline.groovy
    type: JenkinsPipeline
status:
  lastVersion: 0