apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: basic-ui-config
parameters:
- description: Defines the namespace within which these objects are deployed
  name: NAMESPACE
  required: true
- description: Defines name of the microservice
  name: MICROSERVICE
  value: basic-ui
  required: true
- description: Defines max memory
  name: MAX_MEMORY
  value: 400Mi
  required: true  
- description: Defines min memory
  name: MIN_MEMORY
  value: 50Mi
  required: true
- description: Defines docker registry
  name: DOCKER_REGISTRY
  value: docker-registry.default.svc:5000
  required: true      
- description: Defines docker registry
  name: DOCKER_IMAGE_LABEL
  required: true  
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${MICROSERVICE}
    name: ${MICROSERVICE}
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${MICROSERVICE}
      deploymentconfig: ${MICROSERVICE}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${MICROSERVICE}
          product: microservices-scrum
          deploymentconfig: ${MICROSERVICE}
      spec:
        containers:
          - env:
              - name: PROJECT_API_SERVICE_URI
                value: 'http://project-api.${NAMESPACE}.svc:8080'
              - name: PROJECT_BURNDOWN_SERVICE_URI
                value: 'http://project-burndown.${NAMESPACE}.svc:8080'
              - name: SPRINT_API_SERVICE_URI
                value: 'http://sprint-api.${NAMESPACE}.svc:8080'
              - name: SPRINT_BOARD_API_SERVICE_URI
                value: 'http://sprint-board.${NAMESPACE}.svc:8080'
              - name: SPRINT_BURNDOWN_SERVICE_URI
                value: 'http://sprint-burndown.${NAMESPACE}.svc:8080'
              - name: STORY_API_SERVICE_URI
                value: 'http://story-api.${NAMESPACE}.svc:8080'
              - name: TASK_API_SERVICE_URI
                value: 'http://task-api.${NAMESPACE}.svc:8080'          
            image: ${DOCKER_REGISTRY}/${NAMESPACE}/${MICROSERVICE}:${DOCKER_IMAGE_LABEL}
            imagePullPolicy: Always
            name: ${MICROSERVICE}
            ports:
              - containerPort: 8778
                protocol: TCP
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
            readinessProbe:
              failureThreshold: 10
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
            resources:
              limits:
                cpu: '1'
                memory: ${MAX_MEMORY}
              requests:
                cpu: 50m
                memory: ${MIN_MEMORY}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - ${MICROSERVICE}
          from:
            kind: ImageStreamTag
            name: "${MICROSERVICE}:${DOCKER_IMAGE_LABEL}"
            namespace: ${NAMESPACE}
        type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${MICROSERVICE}
    name: ${MICROSERVICE}
    namespace: ${NAMESPACE}
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      - name: 8443-tcp
        port: 8443
        protocol: TCP
        targetPort: 8443
      - name: 8778-tcp
        port: 8778
        protocol: TCP
        targetPort: 8778
    selector:
      app: ${MICROSERVICE}
      deploymentconfig: ${MICROSERVICE}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: basic-ui
    name: basic-ui
    namespace: ${NAMESPACE}
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: basic-ui
      weight: 100
    wildcardPolicy: None